Repository JUNNETWORKS/42-ft_transcendence, pull requests merged in 2022-12, with the labels that each got.

#173 bugfix: `seed.ts`で追加されるユーザのIDがランダムに並び替えられる
  backend/prisma/seed.ts
Labels: bug

#175 174 ゲームマッチが終了したらその結果をDBに保存する
  backend/prisma/schema.prisma
  backend/src/pong/dto/pong-match-making-entry.dto.ts
  backend/src/pong/game/PostMatchStrategy.ts
  backend/src/pong/game/ongoing-matches.ts
  backend/src/pong/game/online-match.ts
  backend/src/pong/game/waiting-queue.ts
  backend/src/pong/game/waiting-queues.ts
  backend/src/pong/pong.gateway.ts
  backend/src/pong/pong.module.ts
  backend/src/pong/pong.service.ts
  frontend/src/features/Pong/components/TopPage.tsx
Labels: DB

#196 球の射出角度を制限する
  backend/src/pong/game/match.ts
Labels: SMALL

#165 チャット/DMが画面いっぱいに広がるようにする
  frontend/src/features/Chat/Chat.tsx
  frontend/src/features/DM/DmPage.tsx
  frontend/src/providers/Layout.tsx
Labels: SMALL

#168 チャット系の発言ボタンを入力欄の右側に置く
  frontend/src/components/CommandCard.tsx
  frontend/src/features/DM/DmCard.tsx
  frontend/src/utils/react.ts
Labels: SMALL

#188 AppRoutes(アプリ全体ルータ)のフォールバックを設定する
  frontend/src/routes/AppRoutes.tsx
Labels: SMALL

#216 トップページから`/pong`, `/chat`, `/me`へのリンクを張る
  frontend/src/components/NavBar.tsx
  frontend/src/features/Index/Index.tsx
Labels: SMALL

#205 ft_open削除
  backend/src/chat/chat.gateway.ts
  backend/src/chatrooms/dto/operation-open.dto.ts
  frontend/src/features/Chat/command.ts
Labels: SMALL

#218 NavBarクリックでユーザモーダルを開かず`/me`に遷移する
  backend/src/users/users.controller.ts
  frontend/src/components/NavBar.tsx
Labels: SMALL

#226 現在のパスに応じて左上の表示を変える
  frontend/src/components/NavBar.tsx
Labels: SMALL

#227 全てのルートをAuthでガードする
  frontend/src/routes/AppRoutes.tsx
Labels: SMALL

#229 ログインしていない時右上に「LOGIN」とわざわざ出さない
  frontend/src/components/NavBar.tsx
Labels: SMALL

#236 `<UserProfileModal>`削除
  frontend/src/features/User/UserProfileModal.tsx
Labels: SMALL

#258 `GET /users/:id/match/results`において、opponentとして「自分」(=に対応するユーザ)が返ってくる
  backend/src/pong/pong.service.ts
Labels: bug

#267 2FA有効化時のダイアログで"iOS"のリンク先がgoogle playになっている
  frontend/src/features/User/components/AuthBlock.tsx
Labels: bug, SMALL

#260 モーダル内に`UserCard`を出すと背景がグレイ
  frontend/src/features/User/UserCard.tsx
Labels: bug, SMALL

#262 `UserCard`の`User Page`ボタンを押して遷移してもモーダルが閉じない
  frontend/src/features/User/UserCard.tsx
  frontend/src/features/User/UserCardHolder.tsx
Labels: bug, SMALL

#277 試合数0のユーザのStatsで勝率が`null%`になる
  backend/src/pong/pong.service.ts
  frontend/src/features/User/components/Stats.tsx
Labels: bug, SMALL

#264 DM新規作成UI
  backend/src/users/users.service.ts
  frontend/src/features/Chat/Chat.tsx
  frontend/src/features/Chat/RoomSetting.tsx
  frontend/src/features/Chat/components/InvitePrivateCard.tsx
  frontend/src/features/Chat/components/InvitePrivateUserList.tsx
  frontend/src/features/Chat/components/UserSelectList.tsx
  frontend/src/features/DM/DmCard.tsx
  frontend/src/features/DM/DmPage.tsx
  frontend/src/features/DM/components/CreateDMCard.tsx
  frontend/src/typedef.ts
Labels: Core

#304 右上クリックでauthではなくmeに飛ばす
  frontend/src/components/NavBar.tsx
Labels: SMALL

#330 マッチヒストリーの勝敗が全部LOSEになるバグを修正
  frontend/src/features/User/MyPage.tsx
  frontend/src/features/User/UserView.tsx
  frontend/src/features/User/components/HistoryCard.tsx
  frontend/src/features/User/components/MatchHistory.tsx
  frontend/src/features/User/types/MatchResult.ts
Labels: bug

#325 bugfix: プライベートマッチ募集時にステータスがPlayingにならないようにする
  backend/src/pong/game/waiting-queue.ts
  backend/src/pong/pong.service.ts
Labels: bug, SMALL

#341 定数を `constants.ts` にまとめる
  frontend/src/components/UserAvater.tsx
  frontend/src/constants.ts
  frontend/src/features/Chat/components/InvitePrivateCard.tsx
  frontend/src/features/DM/components/CreateDMCard.tsx
  frontend/src/features/DevAuth/auth.ts
  frontend/src/hooks/useAPICaller.ts
Labels: SMALL

#344 チャットルームの作成・編集モーダルでルームタイプを変更しようとすると見切れる
  frontend/src/components/Modal.tsx
  frontend/src/features/Chat/RoomSetting.tsx
  frontend/src/features/DevAuth/AuthCard.tsx
  frontend/src/features/User/MyPage.tsx
  frontend/src/features/User/components/AuthBlock.tsx
  frontend/src/hooks/useConfirmModal.tsx
Labels: SMALL

#350 Patch #294
  frontend/src/features/Chat/RoomSetting.tsx
  frontend/src/features/Chat/components/RoomPasswordInput.tsx
Labels: SMALL

#352 ゲーム時間を短くするためのトリック
  backend/src/pong/game/match.ts
Labels: SMALL

#361 プライベートマッチモーダルでもはみ出る
  frontend/src/features/Pong/components/PrivateMatchCard.tsx
Labels: bug, SMALL

#363 `/user/:id`を直接表示するとステータスが必ずオフラインになる
  backend/src/chat/chat.gateway.ts
  backend/src/users/users.controller.ts
  backend/src/ws-server/ws-server.gateway.ts
Labels: bug, SMALL

#368 不要なエンドポイントの削除 & ガード付加
  backend/src/users/users.controller.ts
  frontend/src/features/Chat/components/UserSelectList.tsx
  frontend/src/features/DevAuth/hooks.ts
Labels: Core, SMALL, Final

#373 入れ子になったsuspenseがwarningを出す
  frontend/src/features/User/UserView.tsx
  frontend/src/features/User/components/MatchHistory.tsx
  frontend/src/features/User/components/Stats.tsx
Labels: bug, Core, SMALL, Final

#370 チャットルームまわりの認可処理がおかしい
  backend/src/chat/chat.gateway.ts
  frontend/src/features/Socket/SocketHolder.tsx
  frontend/src/stores/structure.ts
Labels: bug, Core, SMALL, Final

#374 手直し
  frontend/src/features/DevAuth/auth.ts
  frontend/src/features/User/MyPage.tsx
Labels: SMALL

#358 force login 削除
  backend/src/auth/auth.controller.ts
  frontend/src/features/DevAuth/AuthCard.tsx
Labels: Core
